Text Summarization with TF-IDF 
* High-level outline
* Split the document into sentences
* Score each sentence based on word frequency
* Rank the sentences based on their scores
* Summary is the top ranked sentences


In [1]:
#nltk.sent_tokenize(my_text) # Split the text into sentences
#Build TF-IDF, treat each sentence as a document
#We only need the document that we want to summarize

In [2]:
#score = Average(non-zero TF-IDF values)

*TODO:*
* Pick an article
* Split the article into sentences
* Compute the TF-IDF matrix from list of sentences
* Score each sentence by taking average of non-zero TF-IDF values
* Sort each sentence by score
* Print the top scoring sentences as the summary

In [59]:
#pick a random article 
import random
import numpy as np
import pandas as pd
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer


df = pd.read_csv(r'data\bbc_text_cls.csv')

np.random.seed(44)

#a random article as an article 1
article1 = df['text'][np.random.randint(0, len(df))]
article2 = df['text'][np.random.randint(0, len(df))]
article3 = df['text'][np.random.randint(0, len(df))]
article4 = df['text'][np.random.randint(0, len(df))]
article5 = df['text'][np.random.randint(0, len(df))]

news_articles = [article1, article2, article3, article4, article5]
article = random.choice(news_articles)

In [60]:
article

'Galloway targets \'New Labour\' MP\n\nGeorge Galloway is to stand against pro-Iraq war Labour MP Oona King at the next general election.\n\nMr Galloway, who on Thursday won £150,000 in libel damages from the Daily Telegraph said he would contest Bethnal Green, in London, for Respect. The Glasgow Kelvin MP, who was expelled from Labour over his anti Iraq war stance, accused Ms King of being a "New Labour stooge". Ms King said she was "delighted" at the chance to take on Mr Galloway.\n\nMr Galloway\'s current constituency is set to disappear under planned boundary changes in Scotland.\n\nThe 50-year-old MP launched Respect, the Unity Coalition, in January along with 1,000 anti-war activists, and the Muslim Association of Britain. The party\'s declared aims are an end to the occupation of Iraq, the repeal of anti-union laws and the end of privatisation. Speaking from a cafe in Brick Lane, east London, Mr Galloway said he had accepted the party\'s invitation to stand with "great honour an

In [61]:
#split the article into sentences
sentences = nltk.sent_tokenize(article)
sentences

["Galloway targets 'New Labour' MP\n\nGeorge Galloway is to stand against pro-Iraq war Labour MP Oona King at the next general election.",
 'Mr Galloway, who on Thursday won £150,000 in libel damages from the Daily Telegraph said he would contest Bethnal Green, in London, for Respect.',
 'The Glasgow Kelvin MP, who was expelled from Labour over his anti Iraq war stance, accused Ms King of being a "New Labour stooge".',
 'Ms King said she was "delighted" at the chance to take on Mr Galloway.',
 "Mr Galloway's current constituency is set to disappear under planned boundary changes in Scotland.",
 'The 50-year-old MP launched Respect, the Unity Coalition, in January along with 1,000 anti-war activists, and the Muslim Association of Britain.',
 "The party's declared aims are an end to the occupation of Iraq, the repeal of anti-union laws and the end of privatisation.",
 'Speaking from a cafe in Brick Lane, east London, Mr Galloway said he had accepted the party\'s invitation to stand with 

In [62]:
tfidf = TfidfVectorizer(stop_words='english')
response = tfidf.fit_transform(sentences)
response

<20x168 sparse matrix of type '<class 'numpy.float64'>'
	with 248 stored elements in Compressed Sparse Row format>

In [63]:
#take average of non_zero tfidf values
scores = np.mean(response.toarray(), axis=1)
scores

array([0.02159472, 0.02333557, 0.02165665, 0.01543913, 0.01840456,
       0.02367979, 0.01912166, 0.02336708, 0.0177454 , 0.02376283,
       0.01316706, 0.01736206, 0.01681136, 0.02642429, 0.02133683,
       0.02277065, 0.02289926, 0.0210853 , 0.01665748, 0.02026905])

In [64]:
#sort the sentences based on the scores
ranked_sentences = [sentences[index] for index in scores.argsort()[::-1]]
ranked_sentences


["In June's European Parliament elections, Respect failed to gain enough votes for an MEP but did come first in Tower Hamlets borough, most of which is covered by the Commons constituency of Bethnal Green and Bow.",
 '"A stooge who will sing any song, make any speech, do any dance, do anything she is told to by Tony Blair - irrespective of how her constituents are adversely affected or how strongly they feel to the contrary."',
 'The 50-year-old MP launched Respect, the Unity Coalition, in January along with 1,000 anti-war activists, and the Muslim Association of Britain.',
 'Speaking from a cafe in Brick Lane, east London, Mr Galloway said he had accepted the party\'s invitation to stand with "great honour and pride".',
 'Mr Galloway, who on Thursday won £150,000 in libel damages from the Daily Telegraph said he would contest Bethnal Green, in London, for Respect.',
 'Both the Conservatives and the Liberal Democrats have chosen prospective parliamentary candidates for Bethnal Green an

In [65]:
summary = ' '.join(ranked_sentences[0:3])
summary

'In June\'s European Parliament elections, Respect failed to gain enough votes for an MEP but did come first in Tower Hamlets borough, most of which is covered by the Commons constituency of Bethnal Green and Bow. "A stooge who will sing any song, make any speech, do any dance, do anything she is told to by Tony Blair - irrespective of how her constituents are adversely affected or how strongly they feel to the contrary." The 50-year-old MP launched Respect, the Unity Coalition, in January along with 1,000 anti-war activists, and the Muslim Association of Britain.'

Alternatively:

In [66]:
df.head()

text    labels
0  Ad sales boost Time Warner profit\n\nQuarterly...  business
1  Dollar gains on Greenspan speech\n\nThe dollar...  business
2  Yukos unit buyer faces loan claim\n\nThe owner...  business
3  High fuel prices hit BA's profits\n\nBritish A...  business
4  Pernod takeover talk lifts Domecq\n\nShares in...  business

In [71]:
doc = df[df.labels == 'tech']['text'].sample(random_state=44)

In [72]:
doc

1911    Voters flock to blog awards site\n\nVoting is ...
Name: text, dtype: object

In [73]:
import textwrap

def wrap(x):
    return textwrap.fill(x, replace_whitespace=False, fix_sentence_endings=True, width=80)

In [75]:
print(wrap(doc.iloc[0]))

Voters flock to blog awards site

Voting is under way for the annual Bloggies
which recognise the best web blogs - online spaces where people publish their
thoughts - of the year.

Nominations were announced on Sunday, but traffic to
the official site was so heavy that the website was temporarily closed because
of too many visitors.  Weblogs have been nominated in 30 categories, from the
top regional blog, to the best-kept-secret blog.  Blogs had a huge year, with a
top US dictionary naming "blog" word of 2004. Technorati, a blog search engine,
tracks about six million blogs and says that more than 12,000 are added daily.
A blog is created every 5.8 seconds, according to US research think-tank Pew
Internet and American Life, but less than 40% of the total are updated at least
once every two months.

Nikolai Nolan, who has run the Bloggies for the past
five years, told the BBC News website he was not too surprised by the amount of
voters who crowded the site.  "The awards always get a l

In [76]:
sentences = nltk.sent_tokenize(doc.iloc[0].split('\n', 1)[1]) #iloc to get the first row as a string

In [77]:
sentences

['\nVoting is under way for the annual Bloggies which recognise the best web blogs - online spaces where people publish their thoughts - of the year.',
 'Nominations were announced on Sunday, but traffic to the official site was so heavy that the website was temporarily closed because of too many visitors.',
 'Weblogs have been nominated in 30 categories, from the top regional blog, to the best-kept-secret blog.',
 'Blogs had a huge year, with a top US dictionary naming "blog" word of 2004.',
 'Technorati, a blog search engine, tracks about six million blogs and says that more than 12,000 are added daily.',
 'A blog is created every 5.8 seconds, according to US research think-tank Pew Internet and American Life, but less than 40% of the total are updated at least once every two months.',
 'Nikolai Nolan, who has run the Bloggies for the past five years, told the BBC News website he was not too surprised by the amount of voters who crowded the site.',
 '"The awards always get a lot of t

In [78]:
featurizer = TfidfVectorizer(stop_words='english', norm="l1")

In [79]:
X = featurizer.fit_transform(sentences)

In [80]:
def get_sentence_score(tfidf_row):
    #return the average of non-zero values
    #of the tfidf vector representing a sentence
    x = tfidf_row[tfidf_row.nonzero()]
    return np.mean(x)

In [81]:
scores = np.zeros(len(sentences))
for i in range (len(sentences)):
    scores[i] = get_sentence_score(X[i])

In [82]:
scores

array([0.07142857, 0.09090909, 0.11111111, 0.125     , 0.08333333,
       0.06666667, 0.07142857, 0.09090909, 0.16666667, 0.2       ,
       0.07692308, 0.14285714, 0.125     , 0.1       , 0.05263158,
       0.07692308, 0.25      , 0.25      , 0.07142857, 0.33333333,
       0.04761905, 0.2       , 0.09090909, 0.2       , 0.16666667,
       0.11111111])

In [83]:
sort_index = np.argsort(-scores)

In [84]:
#Many options for how to choose which sentences to include:

#1) Choose the top N sentences
#2) Choose sentences until a certain threshold is reached
#3) Choose sentences until a certain number of words is reached
#4) Choose top X& sentences or top X% words
#5) Choose sentences with scores > average score

In [85]:
print("Generated Summary:")
for i in sort_index[0:5]:
    print(wrap("%.2f: %s" % (scores[i], sentences[i])))

Generated Summary:
0.33: Podcasting has also made an appearance in the category.
0.25: This is for the top "replicating idea that spread about weblogs".
0.25: Included in the other categories is best "meme".
0.20: One of the categories that was scrapped though was best music blog.
0.20: Many are done by those who already have text-based blogs, so they are
almost like audio blogs.


In [86]:
doc.iloc[0].split('\n', 1)[0]

'Voters flock to blog awards site'

In [87]:
def summarize(text):
    #extract sentences
    sentences = nltk.sent_tokenize(text)
    
    #perform tfidf
    x = featurizer.fit_transform(sentences)
    
    #compute sentence scores
    scores = np.zeros(len(sentences))
    for i in range (len(sentences)):
        scores[i] = get_sentence_score(x[i])
        
    #sort sentences by score
    sort_index = np.argsort(-scores)
    
    #print summary
    for i in sort_index[0:5]:
        print(wrap("%.2f: %s" % (scores[i], sentences[i])))
        
    return  " ".join([sentences[i] for i in sort_index[0:5]])

summarize(doc.iloc[0])
        

0.33: Podcasting has also made an appearance in the category.
0.25: This is for the top "replicating idea that spread about weblogs".
0.25: Included in the other categories is best "meme".
0.20: Many are done by those who already have text-based blogs, so they are
almost like audio blogs.
0.20: Several entries reflected specific news events.


'Podcasting has also made an appearance in the category. This is for the top "replicating idea that spread about weblogs". Included in the other categories is best "meme". Many are done by those who already have text-based blogs, so they are almost like audio blogs. Several entries reflected specific news events.'

In [88]:
#Let's see the original article
print(wrap(doc.iloc[0]))

Voters flock to blog awards site

Voting is under way for the annual Bloggies
which recognise the best web blogs - online spaces where people publish their
thoughts - of the year.

Nominations were announced on Sunday, but traffic to
the official site was so heavy that the website was temporarily closed because
of too many visitors.  Weblogs have been nominated in 30 categories, from the
top regional blog, to the best-kept-secret blog.  Blogs had a huge year, with a
top US dictionary naming "blog" word of 2004. Technorati, a blog search engine,
tracks about six million blogs and says that more than 12,000 are added daily.
A blog is created every 5.8 seconds, according to US research think-tank Pew
Internet and American Life, but less than 40% of the total are updated at least
once every two months.

Nikolai Nolan, who has run the Bloggies for the past
five years, told the BBC News website he was not too surprised by the amount of
voters who crowded the site.  "The awards always get a l

TextRank

In [89]:
from sklearn.metrics.pairwise import cosine_similarity
#compute similarity matrix
S = cosine_similarity(X)

In [90]:
#sanity check 1
S.shape

(26, 26)

In [91]:
#sanity check 2
len(sentences)

26

In [92]:
#normalize similarity matrix
S /= S.sum(axis=1, keepdims=True)

In [93]:
S[0].sum()

1.0

In [94]:
#uniform transition matrix
U = np.ones_like(S) / len(S)

In [95]:
U[0].sum()

1.0

In [96]:
#smoothed similarity matrix
factor = 0.15
S = factor * U + (1 - factor) * S


In [97]:
S[0].sum()

0.9999999999999999

In [98]:
#find the limiting/stationary distribution
eigenvalues, eigenvectors = np.linalg.eig(S.T) #column vectors instead of row vectors

In [99]:
eigenvalues

array([1.        , 0.85      , 0.1973805 , 0.21404042, 0.22410783,
       0.25817409, 0.27538405, 0.76476295, 0.74524163, 0.72186333,
       0.71598303, 0.6643717 , 0.650821  , 0.65737431, 0.33250475,
       0.59036825, 0.5846095 , 0.37185596, 0.3829547 , 0.54364496,
       0.51432055, 0.49897741, 0.47260399, 0.46258972, 0.41944837,
       0.41497906])

In [100]:
eigenvectors[:, 0] 

array([-0.25358391, -0.174233  , -0.25156031, -0.20870332, -0.18358953,
       -0.15673951, -0.18403745, -0.16489866, -0.20080612, -0.16233786,
       -0.19737093, -0.20817017, -0.18831979, -0.19382641, -0.25941537,
       -0.1737381 , -0.19019496, -0.16274129, -0.17910544, -0.1627469 ,
       -0.16709509, -0.18609653, -0.24280593, -0.23070393, -0.18615579,
       -0.17051023])

In [101]:
eigenvectors[:, 0].dot(S) #proper eigenvector

array([-0.25358391, -0.174233  , -0.25156031, -0.20870332, -0.18358953,
       -0.15673951, -0.18403745, -0.16489866, -0.20080612, -0.16233786,
       -0.19737093, -0.20817017, -0.18831979, -0.19382641, -0.25941537,
       -0.1737381 , -0.19019496, -0.16274129, -0.17910544, -0.1627469 ,
       -0.16709509, -0.18609653, -0.24280593, -0.23070393, -0.18615579,
       -0.17051023])

In [102]:
limiting_distribution = np.ones(len(S)) / len(S)
threshold = 1e-8
delta = float('inf')
iters = 0
while delta > threshold:
    iters += 1
    #Markov transition
    p = limiting_distribution.dot(S)
    #compute change in limiting distribution
    delta = np.abs(p - limiting_distribution).sum()
    #update limiting distribution
    limiting_distribution = p
    
print("Converged after %d iterations" % iters)

Converged after 48 iterations


In [103]:
limiting_distribution

array([0.05031939, 0.03457356, 0.04991784, 0.04141361, 0.03643021,
       0.03110228, 0.03651909, 0.03272132, 0.03984654, 0.03221318,
       0.03916489, 0.04130781, 0.03736885, 0.03846154, 0.05147655,
       0.03447536, 0.03774094, 0.03229323, 0.03554041, 0.03229435,
       0.03315717, 0.03692768, 0.04818069, 0.04577925, 0.03693944,
       0.03383484])

In [104]:
limiting_distribution.sum()

0.9999999999999984

In [105]:
np.abs(eigenvectors[:, 0] / eigenvectors[:, 0].sum() - limiting_distribution).sum()

2.8680860016810916e-08

In [106]:
scores = limiting_distribution #TextRank scores

In [107]:
sort_index = np.argsort(-scores)

In [108]:
print("Generated Summary:")
for i in sort_index[0:5]:
    print(wrap("%.2f: %s" % (scores[i], sentences[i])))

Generated Summary:
0.05: In a sign that blogs are playing an increasingly key part in spreading
news and current affairs, The South-East Asia Earthquake and Tsunami Blog is
also nominated in the best overall category.
0.05: 
Voting is under way for the annual Bloggies which recognise the best web
blogs - online spaces where people publish their thoughts - of the year.
0.05: Weblogs have been nominated in 30 categories, from the top regional blog,
to the best-kept-secret blog.
0.05: Three new categories have been added to the list this year, including best
food, best entertainment, and best writing of a weblog.
0.05: One of the categories that was scrapped though was best music blog.


In [109]:
doc.iloc[0].split('\n')[0]

'Voters flock to blog awards site'

In [110]:
def summarize(text, factor=0.15, threshold=1e-8):
    #extract sentences
    sentences = nltk.sent_tokenize(text)
    
    #perform tfidf
    x = featurizer.fit_transform(sentences)
    
    #compute similarity matrix
    S = cosine_similarity(x)
    
    #normalize similarity matrix
    S /= S.sum(axis=1, keepdims=True)
    
    #uniform transition matrix
    U = np.ones_like(S) / len(S)
    
    #smoothed similarity matrix
    S = factor * U + (1 - factor) * S
    
    #find the limiting/stationary distribution
    limiting_distribution = np.ones(len(S)) / len(S)
    delta = float('inf')
    iters = 0
    while delta > threshold:
        iters += 1
        #Markov transition
        p = limiting_distribution.dot(S)
        #compute change in limiting distribution
        delta = np.abs(p - limiting_distribution).sum()
        #update limiting distribution
        limiting_distribution = p
    
    #print summary
    scores = limiting_distribution
    sort_index = np.argsort(-scores)
    for i in sort_index[0:5]:
        print(wrap("%.2f: %s" % (scores[i], sentences[i])))
        
    return  " ".join([sentences[i] for i in sort_index[0:5]])

In [111]:
summarize(doc.iloc[0])

0.06: Voters flock to blog awards site

Voting is under way for the annual
Bloggies which recognise the best web blogs - online spaces where people publish
their thoughts - of the year.
0.05: In a sign that blogs are playing an increasingly key part in spreading
news and current affairs, The South-East Asia Earthquake and Tsunami Blog is
also nominated in the best overall category.
0.05: Weblogs have been nominated in 30 categories, from the top regional blog,
to the best-kept-secret blog.
0.05: Three new categories have been added to the list this year, including best
food, best entertainment, and best writing of a weblog.
0.05: One of the categories that was scrapped though was best music blog.


'Voters flock to blog awards site\n\nVoting is under way for the annual Bloggies which recognise the best web blogs - online spaces where people publish their thoughts - of the year. In a sign that blogs are playing an increasingly key part in spreading news and current affairs, The South-East Asia Earthquake and Tsunami Blog is also nominated in the best overall category. Weblogs have been nominated in 30 categories, from the top regional blog, to the best-kept-secret blog. Three new categories have been added to the list this year, including best food, best entertainment, and best writing of a weblog. One of the categories that was scrapped though was best music blog.'